<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PTSLO3OM" failures="3" tests="4" name="Test" time="240.701" errors="0" timestamp="2024-04-05T16:27:52 IST">
  <testcase classname="SeleniumProj.AutomateFramework2.OrderHistory" name="viewOrders" time="27.863">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at SeleniumProj.AutomateFramework2.MyOrders.verifyOrders(MyOrders.java:31)
at SeleniumProj.AutomateFramework2.OrderHistory.viewOrders(OrderHistory.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- viewOrders -->
  <testcase classname="SeleniumProj.AutomateFramework2.OrderHistory" name="ErrorValidation2" time="15.435">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully#] but found [Login Successfully]">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully#] but found [Login Successfully]
at SeleniumProj.AutomateFramework2.OrderHistory.ErrorValidation2(OrderHistory.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ErrorValidation2 -->
  <testcase classname="SeleniumProj.AutomateFramework2.SubmitOrder" name="submitorder" time="30.374"/>
  <testcase classname="SeleniumProj.AutomateFramework2.SubmitOrder" name="ErrorValidation" time="21.461">
    <failure type="java.lang.AssertionError" message="expected [Login Successfully.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Login Successfully.] but found []
at SeleniumProj.AutomateFramework2.SubmitOrder.ErrorValidation(SubmitOrder.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ErrorValidation -->
</testsuite> <!-- Test -->
